name: Upload Release
on:
  release:
    types: [published]
jobs:
  pre-release:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        env:
          pre_release: ${{ github.event.release.prerelease }}
      - run: |
          echo $pre_release
          echo "This is a test to Exec an action from prerelease"
          echo $GIT_CONTEXT
