---
apiVersion: v1
kind: Namespace
metadata:
  name: arkondata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkondata-deploy
  namespace: arkondata
  labels:
    app: arkondata-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: arkondata-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arkondata-app
    spec:
      containers:
        - name: arkondata-app
          image: arkondata-gitops
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 50m

---
apiVersion: v1
kind: Service
metadata:
  name: arkondata-svc
  namespace: arkondata
spec:
  selector:
    app.kubernetes.io/name: arkondata-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: arkondata
  name: ingress-arkondata
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: arkondata-svc
              servicePort: 5000
