name: Pre-Release created
on:
  release:
    types: [created]
jobs:
  pre-release:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: Get conventional commits next version
        uses: ./.github/actions/my-action
        id: cc
        with:
          project: "."
          prefix: ""
      - name: Check next version
        run: |
          if [ ${{ steps.cc.outputs.latest_tag }} = ${{ steps.cc.outputs.calculated_next_version }} ] ; then
          echo "- No changes"
          exit 1
          fi
          echo "NEXT_VERSION:"${{ steps.cc.outputs.calculated_next_version }}
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: dev
          to-tag: ${{ steps.cc.outputs.calculated_next_version }}
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.GIT_TOK }}
          latest: true
      - name: Update release
        uses: kaliber5/action-update-release@v1
        with:
          token: ${{ secrets.GIT_TOK }}
          id: ${{ steps.latest_release.outputs.id }}
          name: rc-${{ steps.cc.outputs.calculated_next_version }}
          tag_name: rc-${{ steps.cc.outputs.calculated_next_version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
      - uses: actions/checkout@master
      - run: |
          echo $pre_release
          echo "This is a test to Exec an action from prerelease"
        env:
          pre_release: ${{ github.event.release.tag_name }}
