name: Pre-Release created
on:
  release:
    types: [created]
jobs:
  pre-release:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo $pre_release
          echo "This is a test to Exec an action from prerelease"
        env:
          pre_release: ${{ github.event.release.tag_name }}
